### PR TITLE
Fix gateway_ip ansible var for ctlplane

### PR DESCRIPTION
**Pull request by rabi**
Replaces `gateway_ip` with `ctlplane_gateway_ip`.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by rabi** [comment]
Failed to run 'make crc_storage' target

**Review by slagle — APPROVED** [review]

**Comment by rabi** [comment]
> > @rabi: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/dataplane-operator-build-deploy-kuttl 	[cb68860](https://github.com/openstack-k8s-operators/dataplane-operator/commit/cb68860acf1f50e076e71ff6c58e124c6ff9b257) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/379/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1697242933754859520) 	true 	`/test dataplane-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=dataplane-operator&pr=379). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:rabi).
> 
> I've seen this fail twice in this manner:
> 
> ```
> --- FAIL: kuttl/harness/dataplane-create-test (603.50s)
> ```
> 
> Maybe it's not just a hiccup?

Not related to PR though. It did pass the kuttl tests few times and failed with errors later.

**Pull request merged**
