### PR TITLE
Use dhcp and ovn agent images from OpenstackVersion

### PR DESCRIPTION
**Pull request by karelyatin**
Related-Issue: [OSPRH-6639](https://issues.redhat.com//browse/OSPRH-6639)
Resolves: [OSPRH-6747](https://issues.redhat.com//browse/OSPRH-6747)
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/818

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
+2

**Comment by karelyatin** [comment]
Marked as draft as would require updating go.mod once depends-on pr merges

**Comment by karelyatin** [comment]
> Marked as draft as would require updating go.mod once depends-on pr merges

updated

**Review by slagle — APPROVED** [review]

**Pull request merged**
