### PR TITLE
Support disconnected network environments

### PR DESCRIPTION
**Pull request by dprince**
This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.

For Prow jobs we are enabling this via .prow-ci.env

This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.

(NOTE: this currently requires a secure container registry to test)

Jira: [OSP-26486](https://issues.redhat.com//browse/OSP-26486)

### CODE REVIEW

**Comment by bshephar** [comment]
Looks like an issue with the openstack-operator
```
 "The OpenStackControlPlane \"openstack-galera-network-isolation\" is invalid: \n* spec.horizon.template.containerImage: Required value
```

Not seeing any logs from the openstack-operator either.

Same for the kuttl tests:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/411/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1702474383500513280#1:build-log.txt%3A654

**Comment by bshephar** [comment]
Right, so this is the error from OLM:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/411/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1702535752342048768/artifacts/dataplane-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-62a865e00c09e1aa67ecdaa918307bca6aedf119a71179f5ab17d4ff627781b9/namespaces/openshift-operator-lifecycle-manager/pods/olm-operator-6bf7ddf856-vhzgd/olm-operator/olm-operator/logs/current.log
```
2023-09-15T04:48:30.207077019Z I0915 04:48:30.206941       1 event.go:285] Event(v1.ObjectReference{Kind:"ClusterServiceVersion", Namespace:"openstack-operators", Name:"openstack-operator.v0.0.1", UID:"3271e976-6eb4-47d2-a3eb-a4fac905344c", APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"259308", FieldPath:""}): type: 'Warning' reason: 'InstallComponentFailed' install strategy failed: Deployment.apps "openstack-operator-controller-manager" is invalid: [spec.template.spec.containers[1].env[62].name: Required value, spec.template.spec.containers[1].env[63].name: Required value, spec.template.spec.containers[1].env[64].name: Required value, spec.template.spec.containers[1].env[65].name: Required value, spec.template.spec.containers[1].env[66].name: Required value, spec.template.spec.containers[1].env[67].name: Required value, spec.template.spec.containers[1].env[68].name: Required value, spec.template.spec.containers[1].env[69].name: Required value]
```

So it's failing to install the openstack-operator because of this. Although, I don't see this issue in other jobs, so somehow it seems to be related to this PR.

**Comment by bshephar** [comment]
Rebased on main after the dataplaneDeployment CR merge and resolved the related conflicts.

**Comment by abays** [comment]
> @dprince: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/dataplane-operator-build-deploy-kuttl 	[96da19c](https://github.com/openstack-k8s-operators/dataplane-operator/commit/96da19c9fee0c39aa433e590b85d46da29c6893a) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/411/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1703926756026617856) 	true 	`/test dataplane-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=dataplane-operator&pr=411). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:dprince).

It looks like the ENV var problem persists:

```
7m19s       Warning   InstallComponentFailed   clusterserviceversion/openstack-operator.v0.0.1                         install strategy failed: Deployment.apps "openstack-operator-controller-manager" is invalid: [spec.template.spec.containers[1].env[62].name: Required value, spec.template.spec.containers[1].env[63].name: Required value, spec.template.spec.containers[1].env[64].name: Required value, spec.template.spec.containers[1].env[65].name: Required value, spec.template.spec.containers[1].env[66].name: Required value, spec.template.spec.containers[1].env[67].name: Required value, spec.template.spec.containers[1].env[68].name: Required value, spec.template.spec.containers[1].env[69].name: Required value]
```

https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/411/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1703926756026617856/artifacts/dataplane-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-070a98749455b097c66a1a25ff827a3c0ee7385f1f0c8bf54f5b15438501f2bd/namespaces/openstack-operators/events.log

**Comment by bshephar** [comment]
Rebased on main to fix the merge conflict. Added handling to test each of the customisable images:
https://github.com/openstack-k8s-operators/dataplane-operator/pull/411/files#diff-895b30620b711137530eaebb0cb0b646ce5b123dba340ac85c225f3a648ba49eR50-R54

**Comment by bshephar** [comment]
Back to this error:
```
APIVersion:"operators.coreos.com/v1alpha1", ResourceVersion:"105221", FieldPath:""}): type: 'Warning' reason: 'InstallComponentFailed' install strategy failed: Deployment.apps "openstack-operator-controller-manager" is invalid: [spec.template.spec.containers[1].env[62].name: Required value, spec.template.spec.containers[1].env[63].name: Required value, spec.template.spec.containers[1].env[64].name: Required value, spec.template.spec.containers[1].env[65].name: Required value, 
```
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_dataplane-operator/411/pull-ci-openstack-k8s-operators-dataplane-operator-main-dataplane-operator-build-deploy-kuttl/1704648903808258048/artifacts/dataplane-operator-build-deploy-kuttl/openstack-k8s-operators-gather/artifacts/must-gather/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-62a865e00c09e1aa67ecdaa918307bca6aedf119a71179f5ab17d4ff627781b9/namespaces/openshift-operator-lifecycle-manager/pods/olm-operator-6bf7ddf856-5lkt2/olm-operator/olm-operator/logs/current.log

**Comment by dprince** [comment]
This PR should resolve the CI issues here: https://github.com/openstack-k8s-operators/openstack-operator/pull/480

Doing a bit more digging but it appears there may be an ENV limit which is very concerning as we aren't done adding things yet. Pondering solutions...

**Comment by dprince** [comment]
> This PR should resolve the CI issues here: [openstack-k8s-operators/openstack-operator#480](https://github.com/openstack-k8s-operators/openstack-operator/pull/480)
> 
> Doing a bit more digging but it appears there may be an ENV limit which is very concerning as we aren't done adding things yet. Pondering solutions...

Nah, ETESTING_TOO_MUCH_AT_ONCE. I think the fix above should unblock things and let us move fowards.

**Comment by dprince** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Pull request merged**
