### PR TITLE
Add configmap to ovn service

### PR DESCRIPTION
**Pull request by booxter**
Depends-On: openstack-k8s-operators/ovn-operator#104
Depends-On: openstack-k8s-operators/dataplane-operator#371

### CODE REVIEW

**Comment by booxter** [comment]
This carries the piece from https://github.com/openstack-k8s-operators/dataplane-operator/pull/351 and hence is a draft. Also, the dependency in OVN operator is still a draft.

**Comment by booxter** [comment]
I will rebase when the ovn-operator PR is ready. It still needs some work. Plus I would like to test it end-to-end with edpm-ansible before landing.

**Comment by slawqo** [comment]
LGTM for me, thx

**Review by slagle — COMMENTED** [review]
This exposed a bug in the logic where we weren't resetting the added ExtraMounts in between each service deployment. That is why the kuttl test is failing.

I've fixed the issue here:
https://github.com/openstack-k8s-operators/dataplane-operator/pull/371

Once that is merged, you can rebase this and it should pass.

**Comment by slagle** [comment]
recheck

**Comment by booxter** [comment]
The CI failures are legit, please don't recheck. Looks like the PR that is listed as Depends-On is not fetched?

**Review by karelyatin — COMMENTED** [review]
/lgtm

**Comment by fao89** [comment]
recheck

**Comment by booxter** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Pull request merged**
