### PR TITLE
Split OVN target into a separate Service

### PR DESCRIPTION
**Pull request by booxter**
It will later consume a new ConfigMap prepared by OVN operator.

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Review by slagle — APPROVED** [review]
LGTM, thanks.

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Comment by slagle** [comment]
Looks like I may have messed up resolving the merge conflict for that one kuttl test.

**Review by slagle — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Comment by slagle** [comment]
recheck

**Comment by slagle** [comment]
recheck

**Comment by slagle** [comment]
recheck

**Pull request merged**
