### PR TITLE
Add detailed deployment coditions to nodeset

### PR DESCRIPTION
**Pull request by rabi**
Looking at the nodeset it's difficult to get the detailed status of the deployments running and their service statuses. This adds detailed status of the deployment and it's services. We will further enhance it to add % deployed for the service in cases where we've set max_percentage in the service plays.

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Review by bshephar — APPROVED** [review]
Artefacts of this change, we can see the deployment is updated with nodeSetConditions:
https://review.rdoproject.org/zuul/build/908b794b3fd74526b7839ddbad78f506/log/ci-framework-data/logs/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-c5501ac502209eda400116b0511a5cf07f0537f650b706f63006628472a846af/namespaces/openstack/crs/openstackdataplanedeployments.dataplane.openstack.org/openstack-edpm-ipam.yaml#34

and the nodeSet with deployment conditions:
https://review.rdoproject.org/zuul/build/908b794b3fd74526b7839ddbad78f506/log/ci-framework-data/logs/quay-io-openstack-k8s-operators-openstack-must-gather-sha256-c5501ac502209eda400116b0511a5cf07f0537f650b706f63006628472a846af/namespaces/openstack/crs/openstackdataplanenodesets.dataplane.openstack.org/openstack-edpm-ipam.yaml#179

This should address the requirements raised here:
https://github.com/openstack-k8s-operators/edpm-ansible/pull/494#issuecomment-1832186329

Whereby we will keep a detailed history of executions against the nodeSet that will allow users to make informed decisions about the configuration of their environment.

**Pull request merged**
