### PR TITLE
Simplify deployment watcher for nodeset

### PR DESCRIPTION
**Pull request by rabi**
Removes some api calls and makes the logic a bit simpler.

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Review by fao89 — APPROVED** [review]

**Comment by slagle** [comment]
The Ci failed 3 times, and passed once. Do we care? Is this a system we're relying on to give us accurate test results? At least one of the failures was related to waiting for the condition to be ready on the NodeSet.

**Comment by rabi** [comment]
> The Ci failed 3 times, and passed once. Do we care? Is this a system we're relying on to give us accurate test results? At least one of the failures was related to waiting for the condition to be ready on the NodeSet.

I don't know if the questions/comments were about this PR or edpm jobs in general and probably implies that we `blindly` recheck till the jobs pass, which is incorrect. However, I'll try and explain all the failures in this PR. These jobs do give accurate results other than some known mode of failure (Infra and capacity issues etc) and I never `recheck` without knowing the failure reason. Other than that If there any concerns about the PR we can discuss.

`1st patchset`

Both podified-multinode-edpm-deployment-crc  and cifmw-crc-podified-edpm-baremetal jobs failed waiting for the nodeset to be ready (as you rightly mentioned), because I was filtering on an non-indexed field[1], but you probably missed that it was fixed the next patchset[2]. 


`2nd patchset (1st run)`

`podified-multinode-edpm-deployment-crc`

This failed[3] with error  ` "Wednesday 20 September 2023  03:26:26 -0400 (0:00:00.997)       0:00:01.029 *** ",
2023-09-20 03:26:35.520351 | controller |         "fatal: [crc]: UNREACHABLE! => {\"changed\": false, \"msg\": \"Failed to connect to the host via ssh: kex_exchange_identification: read: Connection reset by peer\\r\\nConnection reset by 38.102.83.196 port 22\", \"unreachable\": true}",` much before anything could be deployed.

`cifmw-crc-podified-edpm-baremetal`

This job failed[4] in `os-net-setup` post completion of dataplane deployment with `fatal: [localhost]: FAILED! => {"changed": false, "msg": "Exception '401\nReason: Unauthorized\nHTTP response headers: HTTPHeaderDict({'Audit-Id': '55e992f8-e9a5-4569-a378-7ba9f2e26001', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Date': 'Wed, 20 Sep 2023 08:13:05 GMT', 'Content-Length': '129'})\nHTTP response body: b'{\"kind\":\"Status\",\"apiVersion\":\"v1\",\"metadata\":{},\"status\":\"Failure\",\"message\":\"Unauthorized\",\"reason\":\"Unauthorized\",\"code\":401}\\n'\nOriginal traceback: \n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 55, in inner\n    resp = func(self, *args, **kwargs)\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/dynamic/client.py\", line 270, in request\n    api_response = self.client.call_api(\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 348, in call_api\n    return self.__call_api(resource_path, method,\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 180, in __call_api\n    response_data = self.request(\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/api_client.py\", line 373, in request\n    return self.rest_client.GET(url,\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 244, in GET\n    return self.request(\"GET\", url,\n\n  File \"/home/zuul/.local/lib/python3.9/site-packages/kubernetes/client/rest.py\", line 238, in request\n    raise ApiException(http_resp=r)\n' raised while trying to get resource using (name=openstack-config, namespace=openstack, label_selectors=[], field_selectors=[])"}` 

2nd patchset (2nd run):

`podified-multinode-edpm-deployment-crc`

Failed running tempest tests[5] as it could not pull the tempest image `fetching blob: received unexpected HTTP status: 500 Internal Server Error"], "stdout": "", "stdout_lines": []}` and I informed the CI team about that in slack.

`cifmw-crc-podified-edpm-baremetal`

Failed with ' net/http: TLS handshake timeout 10082ms` waiting for the nodeset to be ready. That's because this is a slow node and ansibleee jobs could not be finished on time[7].

Hope this clarifies.

[1] https://logserver.rdoproject.org/21/421/733bc186578ab82684f977dcb1b3de7154f8ac97/github-check/cifmw-crc-podified-edpm-baremetal/c812d2a/ci-framework-data/logs/crc/pods/openstack-operators_dataplane-operator-controller-manager-d5948f545-vxh6h_7d541ffc-25c4-4ae2-a4f3-740eecf71d9c/manager/0.log
[2] https://github.com/openstack-k8s-operators/dataplane-operator/compare/733bc186578ab82684f977dcb1b3de7154f8ac97..9d81de87e240bda2e693fc1837a179be7008340d#diff-208c921c448c6050904cd180d04c4cd86319613580ea8e3ac5c6d54eeb471dbdL282

[3] https://logserver.rdoproject.org/21/421/9d81de87e240bda2e693fc1837a179be7008340d/github-check/podified-multinode-edpm-deployment-crc/ae81c75/job-output.txt
[4] https://logserver.rdoproject.org/21/421/9d81de87e240bda2e693fc1837a179be7008340d/github-check/cifmw-crc-podified-edpm-baremetal/cca7eb8/job-output.txt
[5] https://logserver.rdoproject.org/21/421/9d81de87e240bda2e693fc1837a179be7008340d/github-check/podified-multinode-edpm-deployment-crc/67ed03e/job-output.txt
[7] https://logserver.rdoproject.org/21/421/9d81de87e240bda2e693fc1837a179be7008340d/github-check/cifmw-crc-podified-edpm-baremetal/1505ed5/ci-framework-data/logs/crc/pods/openstack_dataplane-deployment-configure-os-openstack-edpm-ipam-mc7tc_cdd811d6-aed3-4b72-8493-b78ccba01d0b/openstackansibleee/0.log

**Comment by slagle** [comment]
> > The Ci failed 3 times, and passed once. Do we care? Is this a system we're relying on to give us accurate test results? At least one of the failures was related to waiting for the condition to be ready on the NodeSet.
> 
> I don't know if the questions/comments were about this PR or edpm jobs in general and probably implies that we `blindly` recheck till the jobs pass, which is incorrect.

What else would be implied if we just see "recheck" and no indication of what the failure was, and if it was even related to an updated commit?

Thanks for your clarifications here. Perhaps keeping a record of why we need to recheck would be best. I'm still seeing a lot of rechecks on a lot of PRs, especially for baremetal failures. Given the recent discussions and frustrations, it's not clear what should be assumed or implied.

If I just see "recheck" with no comments, a link to any issue, a link to a log showing an infra failure, etc, then that's a blind recheck to me.

**Comment by rabi** [comment]
> What else would be implied if we just see "recheck" and no indication of what the failure was, and if it was even related to an updated commit?

We don't recheck for an updated commit to run the jobs and anyone can see the diff clicking the `compare` link.

> If I just see "recheck" with no comments, a link to any issue, a link to a log showing an infra failure, etc, then that's a blind recheck to me.

Not for me, because CI is not yet in the best shape (with mostly vex infra and other crc related issues) and we don't yet have any guidelines to `recheck/retest`  jobs mentioning the error and I've not seen many doing that[1]. Though I agree it would be good to have that guideline in the future. If I'm concerned, I would probably check the failures to know what's the issue.

[1] https://github.com/openstack-k8s-operators/dataplane-operator/pull/378#issuecomment-1698221284

**Pull request merged**
