### PR TITLE
Don't use direct version v1beta1 as package alias

### PR DESCRIPTION
**Pull request by rabi**
This would cause conflicts and make code unreadable.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by rabi** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
```
error: unable to default to a user name: the server is currently unable to handle the request (get users.user.openshift.io ~)
```
recheck

**Comment by fao89** [comment]
recheck

**Pull request merged**
