### PR TITLE
Add neutron-ovn service to deploy this agent on EDP Nodes

### PR DESCRIPTION
**Pull request by karelyatin**
Depends-On: https://github.com/openstack-k8s-operators/neutron-operator/pull/231
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/463
Related-Issue: [OSP-26191](https://issues.redhat.com//browse/OSP-26191)

### CODE REVIEW

**Review by booxter — COMMENTED** [review]
LGTM, waiting for edpm-ansible piece to merge and a new upstream image built for the runner

**Comment by karelyatin** [comment]
dataplane operator image builder / call-build-workflow / operator-index (push)  failing
Wrongly pushed to repo instead of the fork, will recreate PR, closing it and deleting the branch.

**Comment by karelyatin** [comment]
Pushed https://github.com/openstack-k8s-operators/dataplane-operator/pull/485

**Pull request closed without merging**
