### PR TITLE
Add initial envtest for OpenStackDataPlane

### PR DESCRIPTION
**Pull request by bshephar**
This patch mainly just sets up the envtest environment so that it's ready for Ginkgo tests to be defined in future commits. For now, we just validate that we can deploy a OpenStackDataPlane Kind object and that it has Spec and Status fields registered.

### CODE REVIEW

**Comment by bshephar** [comment]
We won't be able to use that ci/prow/unit test if we use envtest. They need to be called with the arguments required to start the envtest k8s environment. Else we will always get that error about no etcd being available:

```
  2023-05-17T03:17:41Z	ERROR	controller-runtime.test-env	unable to start the controlplane	{"tries": 1, "error": "fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory"}
  sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).startControlPlane
  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/envtest/server.go:329
  sigs.k8s.io/controller-runtime/pkg/envtest.(*Environment).Start
  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.6/pkg/envtest/server.go:259
  github.com/openstack-k8s-operators/dataplane-operator/tests/functional.glob..func3
```

The Makefile has the test target which launches the environment correctly. So simply `make test` will run standard Go unit tests with `go test`, along with everything required to launch the envtest environment:
 https://github.com/openstack-k8s-operators/dataplane-operator/pull/187/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R115

**Review by fao89 — APPROVED** [review]
it looks good, but we need to change https://github.com/openshift/release/blob/master/ci-operator/config/openstack-k8s-operators/dataplane-operator/openstack-k8s-operators-dataplane-operator-main.yaml#L45

**Comment by slagle** [comment]
The ci/prow/unit failure is:

```
       unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory 
```

**Comment by fao89** [comment]
> The ci/prow/unit failure is:
> 
> ```
>        unable to start control plane itself: failed to start the controlplane. retried 5 times: fork/exec /usr/local/kubebuilder/bin/etcd: no such file or directory 
> ```
> 
> Do we need add a dependency somewhere on etcd in the CI configuration?

it is the difference between maket test x make gotest @bshephar mentioned above.
I started this: https://github.com/openshift/release/pull/39475

**Comment by fao89** [comment]
this https://github.com/openshift/release/pull/39475 will unblock this PR, can I get a review?

**Pull request merged**
