### PR TITLE
Update status on setup errors

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Review by slagle — APPROVED** [review]

**Comment by fao89** [comment]
ERROR! couldn't resolve module/action 'cifmw.general.ci_script'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/zuul/src/github.com/openstack-k8s-operators/ci-framework/roles/os_must_gather/tasks/main.yml': line 39, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

**Comment by fao89** [comment]
recheck

**Pull request merged**
