### PR TITLE
Remove reboot-os from default services

### PR DESCRIPTION
**Pull request by fao89**

### CODE REVIEW

**Review by fultonj — COMMENTED** [review]
I'm +2 on this as I don't think we should be doing a reboot for every service by default. Only where it's needed. Just wanted to CC @ciecierski since he had done work on that service.

**Comment by fao89** [comment]
recheck

**Review by slagle — COMMENTED** [review]
aren't other services relying on this being included?
playbooks/bootstrap.yml for instance includes kernelargs.yml from edpm_kernel which marks a reboot being needed, and leaves it up to the edpm_reboot role to handle it.

**Comment by fao89** [comment]
I 

> aren't other services relying on this being included? playbooks/bootstrap.yml for instance includes kernelargs.yml from edpm_kernel which marks a reboot being needed, and leaves it up to the edpm_reboot role to handle it.

I didn't know about that, I'll close this PR

**Pull request closed without merging**
