### PR TITLE
Add neutron DHCP agent service definition

### PR DESCRIPTION
**Pull request by slawqo**
Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/375

Related: [OSP-27538](https://issues.redhat.com//browse/OSP-27538)

### CODE REVIEW

**Review by booxter — COMMENTED** [review]
/lgtm

**Comment by karelyatin** [comment]
The failure looks related to the PR:-
resource OpenStackAnsibleEE:openstack/dataplane-deployment-neutron-dhcp-edpm-compute-no-nodes: .status.JobStatus: value mismatch, expected: Succeeded != actual: Running

**Comment by slawqo** [comment]
> The failure looks related to the PR:- resource OpenStackAnsibleEE:openstack/dataplane-deployment-neutron-dhcp-edpm-compute-no-nodes: .status.JobStatus: value mismatch, expected: Succeeded != actual: Running

yes, it's most likely because there was no playbook "neutron_dhcp" in the ansibleee runner image yet.

**Comment by slawqo** [comment]
recheck

**Comment by karelyatin** [comment]
> > The failure looks related to the PR:- resource OpenStackAnsibleEE:openstack/dataplane-deployment-neutron-dhcp-edpm-compute-no-nodes: .status.JobStatus: value mismatch, expected: Succeeded != actual: Running
> 
> yes, it's most likely because there was no playbook "neutron_dhcp" in the ansibleee runner image yet.

I had recheked the job lasttime after edpm-ansible patch merged and image push job ran, but good to confirm

**Comment by booxter** [comment]
I believe it should have pulled the newer runner image, but I still see kuttl failures.

**Comment by slawqo** [comment]
recheck - I don't know what is going on there, locally it's passing for me :/

**Comment by slawqo** [comment]
recheck

**Review by karelyatin — APPROVED** [review]
/lgtm

**Review by fao89 — APPROVED** [review]

**Pull request merged**
