### PR TITLE
Adapted telemetry variable names to the dataplane guidelines

### PR DESCRIPTION
**Pull request by jlarriba**

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
these images also need to be added to config/default/manager_default_images.yaml. That may have been missed when they were first added.

**Comment by jlarriba** [comment]
> these images also need to be added to config/default/manager_default_images.yaml. That may have been missed when they were first added.

Yeah, that was missed when they were added.

**Review by slagle — APPROVED** [review]
thanks

**Comment by jlarriba** [comment]
recheck

`Error from server (NotFound): deployments.apps "nmstate-operator" not found`

**Review by jpodivin — APPROVED** [review]

**Pull request merged**
