### PR TITLE
Add reboot-os service to dataplane-operator

### PR DESCRIPTION
**Pull request by ciecierski**
Add reboot-os service to sample services and add it to default services list.

Depends-On: https://github.com/openstack-k8s-operators/edpm-ansible/pull/503

### CODE REVIEW

**Review by fao89 — COMMENTED** [review]
please update the nodeset samples here:
https://github.com/openstack-k8s-operators/dataplane-operator/tree/main/config/samples
So the CI can test the new service

**Comment by rebtoor** [comment]
if @fao89 request is addressed, it's a +2 for me.

**Comment by slagle** [comment]
> please update the nodeset samples here: https://github.com/openstack-k8s-operators/dataplane-operator/tree/main/config/samples So the CI can test the new service

@bshephar Is in the process of simplifying these samples, and dropping the services (especially if it's the default list) is part of that. That is happening here: https://github.com/openstack-k8s-operators/dataplane-operator/pull/501
So for me, I wouldn't feel the need to block this one on updating those samples, since it will just get removed in the near term anyway.

**Review by slagle — COMMENTED** [review]
per my previous comment, this LGTM

**Comment by fao89** [comment]
but we still need [these samples ](https://github.com/openstack-k8s-operators/install_yamls/blob/main/Makefile#L328-L330)to be updated so the CI can test it

**Review by slagle — COMMENTED** [review]
This LGTM now, just pending the depends-on, https://github.com/openstack-k8s-operators/edpm-ansible/pull/503

**Comment by fao89** [comment]
recheck

**Comment by ciecierski** [comment]
> but we still need [these samples ](https://github.com/openstack-k8s-operators/install_yamls/blob/main/Makefile#L328-L330)to be updated so the CI can test it

Reboot service add to samples

**Review by fao89 — APPROVED** [review]
Thank you!

**Pull request merged**
