### PR TITLE
Remove variables that just set default values

### PR DESCRIPTION
**Pull request by bshephar**
This changes removes any variables from samples that just set default values

### CODE REVIEW

**Comment by lewisdenny** [comment]
recheck

**Review by slagle — COMMENTED** [review]
what about the other samples that also set some of these default values? such as config/samples/dataplane_v1beta1_openstackdataplanenodeset.yaml. shouldn't that be cleaned up as well?

**Comment by rabi** [comment]
This has the same kind of changes as in https://github.com/openstack-k8s-operators/dataplane-operator/pull/621, so let's wait for that to merge and the rebase this.

**Comment by slagle** [comment]
@bshephar Can we close this one out?

**Pull request closed without merging**
