### PR TITLE
Use the same variable name for service related images

### PR DESCRIPTION
**Pull request by fao89**
Nova: https://github.com/openstack-k8s-operators/nova-operator/blob/main/config/default/manager_default_images.yaml

OVN: https://github.com/openstack-k8s-operators/ovn-operator/blob/main/config/default/manager_default_images.yaml

Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/568

### CODE REVIEW

**Comment by fao89** [comment]
failed on OpenStackControlPlane CR
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by bshephar — APPROVED** [review]

**Comment by slawqo** [comment]
I proposed similar change in https://github.com/openstack-k8s-operators/dataplane-operator/pull/535 and tested it in https://review.rdoproject.org/r/c/testproject/+/50872 - it seems to be working fine. So LGTM for me and I will abandon my PR.

**Review by slawqo — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
CI worked here: https://github.com/openstack-k8s-operators/dataplane-operator/pull/537
So the CI failures are related to this PR

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by slawqo — APPROVED** [review]

**Review by slagle — COMMENTED** [review]
@fao89 LGTM. what's the path forward for this one? Do we need to push on getting the depends-on (https://github.com/openstack-k8s-operators/openstack-operator/pull/568) merged?

**Comment by fao89** [comment]
@slagle yes, without https://github.com/openstack-k8s-operators/openstack-operator/pull/568 CI breaks

**Comment by nate-johnston** [comment]
retest

**Comment by mhuin** [comment]
recheck

**Comment by morucci** [comment]
recheck

**Comment by morucci** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
closing in favor of
https://github.com/openstack-k8s-operators/openstack-operator/pull/712
https://github.com/openstack-k8s-operators/dataplane-operator/pull/757

**Comment by fao89** [comment]
recheck

**Pull request closed without merging**
