### PR TITLE
early out if role already deployed

### PR DESCRIPTION
**Pull request by SeanMooney**
This change add a check to early out from
the reconcile loop if the openstack dataplane role
status is deployed and it is not marked for deletion.

role reconciliation once completed should only happen again
if the end user sets deployed to false.
This prevents looping of reconciling the NovaExternalCompute
CRs by preventing the role reconcilation form triggering
a reconciliation of all the NovaExternalComputes.

manually triggering deployment can be done as follows
oc delete -n openstack openstackAnsibleEE dataplane-deployment-validate-network-edpm-compute
oc patch openstackdataplanerole edpm-compute --subresource status --type merge  -p '{"status":{"conditions":[{"type":"validate-network service ready", "status": "Unknown", "lastTransitionTime": "2023-08-03T17:32:39Z" }]}}'
oc patch openstackdataplanerole edpm-compute --subresource status --type json -p='[{"op": "replace", "path": "/status/deployed", "value": false}]'

Closes: #327
(cherry picked from commit f8fb92be31982314526fefdd787abd5a1ba36b6a)
Signed-off-by: Sean Mooney <work@seanmooney.info>

### CODE REVIEW

**Review by slagle — COMMENTED** [review]
+2

**Comment by fao89** [comment]
recheck

**Review by jpodivin — COMMENTED** [review]
I like this.

**Review by fao89 — APPROVED** [review]

**Pull request merged**
