### PR TITLE
Revert: Get inventory data from cluster

### PR DESCRIPTION
**Pull request by fao89**
reverts: https://github.com/openstack-k8s-operators/dataplane-operator/pull/325

probably needs https://github.com/openstack-k8s-operators/install_yamls/pull/472 to be merged first

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Comment by slagle** [comment]
This passed the baremetal job. I'm good to override if the next run doesn't pass.

**Pull request merged**
