### PR TITLE
Added the defaults for Telemetry compute images

### PR DESCRIPTION
**Pull request by jlarriba**

### CODE REVIEW

**Review by abays — COMMENTED** [review]
Code changes look good to me, not sure what happened with Prow CI

**Comment by jlarriba** [comment]
> Code changes look good to me, not sure what happened with Prow CI

I thought that it was that my pre-commit was botched by a go version installation 1.21, but I fixed it and got the same results from Prow

**Review by fao89 — APPROVED** [review]

**Pull request merged**
