### PR TITLE
Mark node ready when role is ready

### PR DESCRIPTION
**Pull request by rabi**
This is a regression from the subconditions PR[1].

[1] https://github.com/openstack-k8s-operators/dataplane-operator/pull/293

### CODE REVIEW

**Review by bshephar — APPROVED** [review]
Thanks Rabi, lgtm.

**Comment by rabi** [comment]
error: unable to default to a user name: the server is currently unable to handle the request (get users.user.openshift.io ~)"

**Comment by rabi** [comment]
recheck

**Pull request merged**
