### PR TITLE
Build network ansible vars for IPAM

### PR DESCRIPTION
**Pull request by rabi**
We provide networks for IPAM, Let's build the network ansible vars from it to avoid inconsistency.

### CODE REVIEW

**Comment by rabi** [comment]
recheck

Looks like ci-framework issue has been fixed with https://github.com/openstack-k8s-operators/ci-framework/pull/610

**Comment by rabi** [comment]
/hold

Though this working we probably have to do it 2 steps i.e changing the samples after dataplane-operator bumped in openstack-operator.

**Comment by rabi** [comment]
recheck

Multinode job fixed now

**Review by slagle — APPROVED** [review]

**Review by bshephar — APPROVED** [review]

**Pull request merged**
