### PR TITLE
Use inventory as a secret instead of configmap

### PR DESCRIPTION
**Pull request by fao89**
Changing it into secret, as the inventory may require secret values.
```
EDPM_OVN_METADATA_AGENT_TRANSPORT_URL=$(oc get secret rabbitmq-transport-url-neutron-neutron-transport -o json | jq -r .data.transport_url | base64 -d)
EDPM_OVN_METADATA_AGENT_PROXY_SHARED_SECRET=$(oc get secret osp-secret -o json | jq -r .data.MetadataSecret  | base64 -d)
```

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
@slagle could you please take another look?

**Comment by rabi** [comment]
+2 LGTM, though secrets are just base64 encoded and by default stored unecrypted in etcd.

**Review by jpodivin — APPROVED** [review]

**Pull request merged**
