### PR TITLE
DNM test edpm jobs

### PR DESCRIPTION
**Pull request by rabi**
Depends-On: https://github.com/openstack-k8s-operators/ci-framework/pull/278
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/345
Depends-On: https://github.com/openstack-k8s-operators/install_yamls/pull/316

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by raukadah** [comment]
recheck

**Pull request closed without merging**
