### PR TITLE
Use MatchingFields instead of MatchingLabels for listing nodes

### PR DESCRIPTION
**Pull request by fao89**
role field will always be there,
the label needs a reconcile loop to be added

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
@raukadah could you please take a look? dataplane-operator-crc-podified-edpm-baremetal  is consistently failing, but doesn't seem related to this PR

**Review by rebtoor — COMMENTED** [review]
+2

**Review by slagle — APPROVED** [review]

**Pull request merged**
