### PR TITLE
Use DNS cluster ips in aee pods

### PR DESCRIPTION
**Pull request by rabi**
We use mcvlan with NADs and when NADs are attached to pods, the metallb ips on the interfaces can't be reached on the same node. With this change we use the cluster ips for dns service so it can reach the service for dns resolution.

### CODE REVIEW

**Review by fao89 — APPROVED** [review]

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by abays** [comment]
> Build failed (check pipeline). For information on how to proceed, see http://docs.openstack.org/infra/manual/developers.html#automated-testing
> 
> https://review.rdoproject.org/zuul/buildset/b56fdf747040486c9aedec96a5bfee24
> 
> ✔️ [dataplane-operator-content-provider ](https://review.rdoproject.org/zuul/build/d8ffef0e12014b15b703059dcb75220c) SUCCESS in 1h 44m 04s x [dataplane-operator-crc-podified-edpm-baremetal ](https://review.rdoproject.org/zuul/build/866a7a6a029e42638d02ecaa246e5c0f) **FAILURE** in 1h 25m 44s heavy_check_mark [dataplane-operator-crc-podified-edpm-deployment ](https://review.rdoproject.org/zuul/build/a02dbd686c3146dabdb06b1594ccc0ea) SUCCESS in 1h 05m 04s

It looks like the `edpm-baremetal` Zuul job is failing across a few PRs with a timeout during the ` Wait for OpenStackDataPlane to be Ready` task.  Is this PR intended to fix that issue?

**Comment by rabi** [comment]
> It looks like the edpm-baremetal Zuul job is failing across a few PRs with a timeout during the  Wait for OpenStackDataPlane to be Ready task. Is this PR intended to fix that issue?

Yes this would fix the issue after NADs were attached edpm ansible pods[1] . Though edpm-baremetal job did not finish here, it went beyond the failure elsewhere[2]. So if we want, we can force merge this.

[1] https://github.com/openstack-k8s-operators/dataplane-operator/pull/325

[2] https://logserver.rdoproject.org/36/336/7bf441e26228590dba0f329d420b5cc05c9ebfcb/github-check/dataplane-operator-crc-podified-edpm-baremetal/866a7a6/ci-framework-data/logs/crc/pods/openstack_dataplane-deployment-configure-network-edpm-compute-gh2vz_835e45ec-71fc-4c11-91fd-d24381d6d80b/openstackansibleee/0.log

**Comment by rabi** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Pull request merged**
