### PR TITLE
Adds docs target to build documentation

### PR DESCRIPTION
**Pull request by raukadah**
It also adds a Zuul job to preview the docs.

### CODE REVIEW

**Comment by raukadah** [comment]
@fao89 @odyssey4me Hello! this pr contains the [zuul job](https://review.rdoproject.org/zuul/build/decc772c7ca64a45ae0d20d9cc88ad0f) to build and preview docs. Here is the generated docs: https://logserver.rdoproject.org/82/282/e00cab9aa95afad791ca946ba0a7d63c5ed31fd4/github-check/dataplane-operator-docs-preview/decc772/docs/ .

**Comment by raukadah** [comment]
recheck

**Review by fao89 — APPROVED** [review]
this is great!

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Pull request merged**
