### PR TITLE
Fix how we use labels and aee name for services

### PR DESCRIPTION
**Pull request by rabi**
Use deployment and nodeset name/uuid in AEE name/label for normal services. 

Use deployment name/uuid in AEE name/label for global services.

This would fix the intermittent failures in functional and kuttl tests due to name collision of AEEs.

### CODE REVIEW

**Comment by jpodivin** [comment]
I'm actually already working on this https://github.com/openstack-k8s-operators/dataplane-operator/pull/744

**Comment by rabi** [comment]
> I'm actually already working on this #744

This is mostly ready other than kuttl assert mismatches which has weird hashes in them. I had looked at your PR and I think we should not complicate it with auto-generated ids. I'm fine if that one is ready earlier.. We need to fix the gate asap. All my prs are blocked by the issue and it's happening frequently.

**Comment by jpodivin** [comment]
> > I'm actually already working on this #744
> 
> This is mostly ready other than kuttl assert mismatches which has weird hashes in them. I had looked at your PR and I think we should not complicate it with auto-generated ids. I'm fine if that one is ready earlier.. We need to fix the gate asap. All my prs are blocked by the issue and it's happening frequently.

If you don't want to collaborate on this it's fine. If your fix works I'm all for it.

**Comment by rabi** [comment]
> If you don't want to collaborate on this it's fine. If your fix works I'm all for it.

Not sure I understand. My intent is to fix the issue ASAP and no way ensure that this PR is merged :smile: From the discussion yesterday I understood that we still don't know what the issue is, that's why I looked at it this morning. Isn't that collaboration where I looked at the issue and trying to fix it?  Anyway, I can drop this PR if you want that PR to go in. The other option is we merge this if this fixes the immediate gate issue and is green. We can refine it in your PR.

**Pull request merged**
