### PR TITLE
Introduce `download-cache` service

### PR DESCRIPTION
**Pull request by rebtoor**

### CODE REVIEW

**Comment by rebtoor** [comment]
retry

**Comment by rebtoor** [comment]
retry

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Review by fao89 — COMMENTED** [review]
+2

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Comment by slagle** [comment]
/hold

In order to avoid a merge conflict, we need to hold this until https://github.com/openstack-k8s-operators/dataplane-operator/pull/303 can be merged. PR 303 is the top priority in order to get merged at this time.

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Comment by slagle** [comment]
/unhold

rdoproject.org/github-check jobs should be passing now.

**Comment by rebtoor** [comment]
recheck

**Comment by rebtoor** [comment]
It seems that the kuttle tests are using the default runner image, not the one created from the patch referenced in `Depends-On`. So i guess this job will fail until https://github.com/openstack-k8s-operators/edpm-ansible/pull/272 get merged.

cc @slagle @fao89

**Comment by fao89** [comment]
@raukadah ^

**Review by fao89 — APPROVED** [review]

**Pull request merged**
