### PR TITLE
Option to select required DDP package

### PR DESCRIPTION
**Pull request by Jaganathancse**

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
recheck

**Review by slagle — CHANGES_REQUESTED** [review]
kuttl test needs to be fixed since a task was added.

     case.go:366: resource OpenStackAnsibleEE:openstack/dataplane-deployment-configure-network-edpm-compute-no-nodes: .spec.roles.tasks: slice length mismatch: 6 != 7

**Pull request closed without merging**
