### PR TITLE
Bump controller-runtime to 0.15

### PR DESCRIPTION
**Pull request by bshephar**
The controller-runtime dependency needs to be updated to 0.15 to fix issues introduce by k8s.io/* v0.27.x This change bumps the controller-runtime dependency which will unblock to k8s.io upgrades.

### CODE REVIEW

**Comment by bshephar** [comment]
We can't merge this until all of our dependent packages implement the required interface changes:
```
❯ go vet ./...
# github.com/openstack-k8s-operators/openstack-ansibleee-operator/api/v1alpha1
../../../go/pkg/mod/github.com/openstack-k8s-operators/openstack-ansibleee-operator/api@v0.0.0-20230523171900-dd4d0945d2d1/v1alpha1/openstackansibleee_webhook.go:76:27: cannot use &OpenStackAnsibleEE{} (value of type *OpenStackAnsibleEE) as admission.Validator value in variable declaration: *OpenStackAnsibleEE does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
# github.com/openstack-k8s-operators/nova-operator/api/v1beta1
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/nova_webhook.go:105:27: cannot use &Nova{} (value of type *Nova) as admission.Validator value in variable declaration: *Nova does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/novaapi_webhook.go:76:27: cannot use &NovaAPI{} (value of type *NovaAPI) as admission.Validator value in variable declaration: *NovaAPI does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/novacell_webhook.go:86:27: cannot use &NovaCell{} (value of type *NovaCell) as admission.Validator value in variable declaration: *NovaCell does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/novaconductor_webhook.go:76:27: cannot use &NovaConductor{} (value of type *NovaConductor) as admission.Validator value in variable declaration: *NovaConductor does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/novaexternalcompute_webhook.go:86:27: cannot use &NovaExternalCompute{} (value of type *NovaExternalCompute) as admission.Validator value in variable declaration: *NovaExternalCompute does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/novametadata_webhook.go:76:27: cannot use &NovaMetadata{} (value of type *NovaMetadata) as admission.Validator value in variable declaration: *NovaMetadata does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/novanovncproxy_webhook.go:76:27: cannot use &NovaNoVNCProxy{} (value of type *NovaNoVNCProxy) as admission.Validator value in variable declaration: *NovaNoVNCProxy does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/openstack-k8s-operators/nova-operator/api@v0.0.0-20230523154806-b03835b62112/v1beta1/novascheduler_webhook.go:76:27: cannot use &NovaScheduler{} (value of type *NovaScheduler) as admission.Validator value in variable declaration: *NovaScheduler does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
# github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1
../../../go/pkg/mod/github.com/metal3-io/baremetal-operator/apis@v0.2.0/metal3.io/v1alpha1/baremetalhost_webhook.go:37:27: cannot use &BareMetalHost{} (value of type *BareMetalHost) as admission.Validator value in variable declaration: *BareMetalHost does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
../../../go/pkg/mod/github.com/metal3-io/baremetal-operator/apis@v0.2.0/metal3.io/v1alpha1/bmceventsubscription_webhook.go:37:27: cannot use &BMCEventSubscription{} (value of type *BMCEventSubscription) as admission.Validator value in variable declaration: *BMCEventSubscription does not implement admission.Validator (wrong type for method ValidateCreate)
		have ValidateCreate() error
		want ValidateCreate() (admission.Warnings, error)
```

It seems we will need to do MariaDB and Keystone first. Then we can look at tackling some of the above issues.

**Comment by rebtoor** [comment]
@bshephar does renovate bot automatically open PRs for this kind of version bump?

**Comment by slagle** [comment]
I don't see this in other operators (I just spot checked a few). Is it still needed?

**Comment by slagle** [comment]
> I don't see this in other operators (I just spot checked a few). Is it still needed?

@bshephar Is this still needed?

**Comment by slagle** [comment]
All our other operators are still at v0.14.6

Closing out this PR due to age. Please re-open it when you (or someone) is able
to start working on it again.

**Pull request closed without merging**
