### PR TITLE
Add make docs to pre-commit

### PR DESCRIPTION
**Pull request by bshephar**

### CODE REVIEW

**Review by fao89 — COMMENTED** [review]
we need this https://github.com/openshift/release/pull/48637

**Review by fao89 — APPROVED** [review]

**Comment by fao89** [comment]
installing ruby wasn't enough, I'm working on https://github.com/openshift/release/pull/48698

**Review by jpodivin — CHANGES_REQUESTED** [review]
I'm not sure this is a good idea. Pre-commit shouldn't take too long to run. It shouldn't really build anything. Instead it should check compliance of newly created commit with existing standard.

**Comment by jpodivin** [comment]
I've run it and it doesn't seem to cause noticeable slowdown. It still needs the prow action fixed, but that's comparatively easy to do.

**Review by jpodivin — APPROVED** [review]

**Pull request merged**
