### PR TITLE
Removing the role field of the OpenStackDataPlaneServiceSpec

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Comment by fao89** [comment]
should we undraft this?

**Comment by fao89** [comment]
recheck

**Review by slagle — APPROVED** [review]

**Comment by jpodivin** [comment]
recheck

**Comment by fao89** [comment]
some kuttl tests need update: https://github.com/openstack-k8s-operators/dataplane-operator/blob/main/tests/kuttl/tests/dataplane-service-custom-image/00-assert.yaml#L122-L132

**Review by fao89 — APPROVED** [review]

**Pull request merged**
