### PR TITLE
Remove ANSIBLE_VERBOSITY from samples

### PR DESCRIPTION
**Pull request by fao89**
ref: https://github.com/openstack-k8s-operators/install_yamls/pull/315

### CODE REVIEW

**Comment by fao89** [comment]
recheck

**Comment by fao89** [comment]
/test dataplane-operator-build-deploy-kuttl
recheck

**Review by bshephar — COMMENTED** [review]
I guess the benefit of it being present in the Sample file was that is demonstrated to users how they can set the Ansible verbosity. Maybe we can follow this up with a documentation PR that explains how to get debug info from Ansible using the operator?

**Comment by fao89** [comment]
> I guess the benefit of it being present in the Sample file was that is demonstrated to users how they can set the Ansible verbosity. Maybe we can follow this up with a documentation PR that explains how to get debug info from Ansible using the operator?

I agree, I need to document the configmap also

**Comment by jpodivin** [comment]
recheck

**Comment by rebtoor** [comment]
recheck

**Review by rebtoor — APPROVED** [review]

**Pull request merged**
