### PR TITLE
structured logging2

### PR DESCRIPTION
**Pull request by pinikomarov**
This automatically adds additional fields like reconcile_id etc.. from the controller context.
and standardize the logging implementation

example logging after patch:

```
2023-10-24T17:30:11+03:00       INFO    Controllers.OpenStackDataPlaneNodeSet   Reconciling DNSData     {"controller": "openstackdatapla
nenodeset", "controllerGroup": "dataplane.openstack.org", "controllerKind": "OpenStackDataPlaneNodeSet", "OpenStackDataPlaneNodeSet": {"
name":"openstack-edpm","namespace":"openstack"}, "namespace": "openstack", "name": "openstack-edpm", "reconcileID": "28cdfd8a-e595-415b-b20b-89b6da5f16e0", "ObjectType": "*v1beta1.OpenStackDataPlaneNodeSet", "ObjectNamespace": "openstack", "ObjectName": "openstack-edpm"}
```

*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.

### CODE REVIEW

**Comment by jpodivin** [comment]
recheck

```
TASK [ci_setup : Gather version of openshift client if it exists _raw_params=oc version -o yaml] ***
Tuesday 24 October 2023  10:35:53 -0400 (0:00:00.753)       0:00:15.602 ******* 
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "oc version -o yaml", "msg": "[Errno 2] No such file or directory: b'oc'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

**Review by slagle — APPROVED** [review]

**Comment by fao89** [comment]
recheck

**Review by slagle — COMMENTED** [review]
Can you fix the commit message? It's not descriptive of the change. What you have in the PR description would also work as the commit message.

**Review by slagle — COMMENTED** [review]
+2

**Comment by pinikomarov** [comment]
recheck

**Comment by slagle** [comment]
@pinikomarov I pushed to your fork in order to resolve the conflicts. Let's see if it passes CI now, than we can move forward with merging it.

**Review by slagle — APPROVED** [review]

**Pull request merged**
