### PR TITLE
Adding cleanup steps to kuttl tests

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Review by SeanMooney — COMMENTED** [review]
oh right that dataplane operator is not using a separate namespace for each kuttl test suite

so yes there could be test interactions without cleaning up.

**Comment by rabi** [comment]
Though it's ok to delete resources explicitly after every test, as I mentioned in the earlier PR the resources are indeed cleaned up. Below is a full kuttl run and resources at different times (note: we're not running tests in parallel)

--- PASS: kuttl (808.89s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/dataplane-create-test (1.07s)
        --- PASS: kuttl/harness/dataplane-extramounts (15.16s)
        --- PASS: kuttl/harness/dataplane-with-ipam-create-test (11.23s)
        --- PASS: kuttl/harness/dataplane-service-custom-image (15.20s)
        --- PASS: kuttl/harness/dataplane-service-config (16.13s)
        --- PASS: kuttl/harness/dataplane-deploy-no-nodes-test (420.45s)
        --- PASS: kuttl/harness/dataplane-deploy-global-service-test (226.31s)
        --- PASS: kuttl/harness/dataplane-deploy-tls-test (102.64s)
PASS


[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
NAME                    STATUS   MESSAGE
edpm-compute-no-nodes   False    Deployment in progress
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanedeployment -n openstack
NAME                    NODESETS                    STATUS   MESSAGE
edpm-compute-no-nodes   ["edpm-compute-no-nodes"]   False    Deployment in progress
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanedeployment -n openstack
NAME                         NODESETS                    STATUS   MESSAGE
edpm-compute-no-nodes        ["edpm-compute-no-nodes"]   True     Setup complete
edpm-compute-no-nodes-ovrd   ["edpm-compute-no-nodes"]   True     Setup complete
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
NAME                    STATUS   MESSAGE
edpm-compute-no-nodes   True     NodeSet Ready
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
NAME                    STATUS   MESSAGE
edpm-compute-no-nodes   False    Deployment in progress
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanedeployment -n openstack
NAME                  NODESETS                  STATUS   MESSAGE
edpm-compute-global   ["edpm-compute-global"]            
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
NAME                  STATUS   MESSAGE
edpm-compute-global   False    Deployment in progress
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
NAME                  STATUS   MESSAGE
edpm-compute-global   False    Deployment in progress
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
NAME                 STATUS   MESSAGE
openstack-edpm-tls   False    Deployment not started
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanedeployment -n openstack
No resources found in openstack namespace.
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanedeployment -n openstack
NAME                 NODESETS                 STATUS   MESSAGE
openstack-edpm-tls   ["openstack-edpm-tls"]   False    Deployment in progress
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanedeployment -n openstack
NAME                      NODESETS                 STATUS   MESSAGE
openstack-edpm-tls        ["openstack-edpm-tls"]   True     Setup complete
openstack-edpm-tls-ovrd   ["openstack-edpm-tls"]   False    Deployment in progress
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
NAME                 STATUS   MESSAGE
openstack-edpm-tls   True     NodeSet Ready
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanenodeset -n openstack
No resources found in openstack namespace.
[stack@osp-df-2 install_yamls]$ oc get openstackdataplanedeployment -n openstack
No resources found in openstack namespace.
[stack@osp-df-2 install_yamls]$ oc get openstackansibleee -n openstack
No resources found in openstack namespace.

**Comment by jpodivin** [comment]
recheck - retry limit

**Review by slagle — COMMENTED** [review]
I don't understand why this is needed. Unless you pass `--skip-delete`, anything created in the tests will be automatically deleted.

What this would do is delete any of these other resources that exist and were created outside the test, but only after the test. So, this doesn't make sense to me, and it would actually make it harder to debug why a test may have failed...

1. fail the first time due to existence of unrelated resources that pollute the test
2. unrelated resources are deleted by 99-cleanup.yml
3. test now passes

very hard to tell why it failed the first time.

**Comment by jpodivin** [comment]
> I don't understand why this is needed. Unless you pass `--skip-delete`, anything created in the tests will be automatically deleted.
> 
> What this would do is delete any of these other resources that exist and were created outside the test, but only after the test. So, this doesn't make sense to me, and it would actually make it harder to debug why a test may have failed...
> 
>     1. fail the first time due to existence of unrelated resources that pollute the test
> 
>     2. unrelated resources are deleted by 99-cleanup.yml
> 
>     3. test now passes
> 
> 
> very hard to tell why it failed the first time.

If I understand the kuttl docs[1] correctly. The automated cleanup does not happen, when the tests are executed in the same namespace. In our case that would be the `openstack`. We could add cleanup tests as test before each test. 

[1] https://kuttl.dev/docs/testing/test-environments.html#single-namespace-testing

**Comment by slagle** [comment]
> > I don't understand why this is needed. Unless you pass `--skip-delete`, anything created in the tests will be automatically deleted.
> > What this would do is delete any of these other resources that exist and were created outside the test, but only after the test. So, this doesn't make sense to me, and it would actually make it harder to debug why a test may have failed...
> > ```
> > 1. fail the first time due to existence of unrelated resources that pollute the test
> > 
> > 2. unrelated resources are deleted by 99-cleanup.yml
> > 
> > 3. test now passes
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > very hard to tell why it failed the first time.
> 
> If I understand the kuttl docs[1] correctly. The automated cleanup does not happen, when the tests are executed in the same namespace. In our case that would be the `openstack`. We could add cleanup tests as test before each test.
> 
> [1] https://kuttl.dev/docs/testing/test-environments.html#single-namespace-testing

That's not the observed behavior. That can be checked in our kuttl test logs. No resources are left behind. Are you seeing differently or is something else already cleaning them up? What issue is this trying to fix?

**Comment by jpodivin** [comment]
> > > I don't understand why this is needed. Unless you pass `--skip-delete`, anything created in the tests will be automatically deleted.
> > > What this would do is delete any of these other resources that exist and were created outside the test, but only after the test. So, this doesn't make sense to me, and it would actually make it harder to debug why a test may have failed...
> > > ```
> > > 1. fail the first time due to existence of unrelated resources that pollute the test
> > > 
> > > 2. unrelated resources are deleted by 99-cleanup.yml
> > > 
> > > 3. test now passes
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > very hard to tell why it failed the first time.
> > 
> > 
> > If I understand the kuttl docs[1] correctly. The automated cleanup does not happen, when the tests are executed in the same namespace. In our case that would be the `openstack`. We could add cleanup tests as test before each test.
> > [1] https://kuttl.dev/docs/testing/test-environments.html#single-namespace-testing
> 
> That's not the observed behavior. That can be checked in our kuttl test logs. No resources are left behind. Are you seeing differently or is something else already cleaning them up? What issue is this trying to fix?

With our tests still being a bit flaky I thought that explicitly removing leftovers from previous test cases could help. Especially since the documentation seemed to indicate that it's necessary if we are defining our own namespace.

But, I understand that the current behavior differs from what would be expected if that was the case.

**Pull request closed without merging**
